title: Bartholomew Walters
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
description: Hello World, welcome to my site!
theme: just-the-docs
color_scheme: dark

permalink: pretty

ga_tracking: G-7MFLNBH8S4

aux_links:
  "Bartholomew on Github":
    - "//github.com/bartk6"
  "Email Me": 
    - "mailto:bartholomew@bwalters.au"


url: https://github.com/bartk6






