title: Bartholomew Walters
description: Hello World, welcome to my site!
theme: just-the-docs
color_scheme: dark

aux_links:
  "Bartholomew on Github":
    - "//github.com/bartk6"



url: https://github.com/bartk6






